---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoring-app
        image: shantanu2001/monitoring-app:latest
        ports:
        - containerPort: 5000   # Use port 5000

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-app-service
spec:
  selector:
    app: monitoring-app
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 5000
    nodePort: 30000          # Optional: specify the node port if needed, otherwise Kubernetes will assign one automatically
  type: NodePort

